/* Scripture trivia: public solo board and private two-account rooms. */
window.TriviaGame=(()=>{
  let root,ctx,library=null,mode=null,room=null,open=null,solo=null,feedback=null,tick=null,poll=null,busy=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function stop(){clearInterval(tick);clearInterval(poll);tick=poll=null}
  function hide(){stop();root=null;room=null;open=null;feedback=null;busy=false}
  function seconds(){return room?Math.max(0,Math.ceil(room.ends_at*1000-Date.now())/1000):Math.max(0,Math.ceil(((solo?.ends||0)-Date.now())/1000))}
  async function load(){if(!library)library=await ctx.api('/study/trivia')}
  function status(){if(room){const me=ctx.user()?.id,opponent=room.host.id===me?room.guest:room.host;return `<div class="trivia-status"><span>${esc(room.host.name)} ${room.scores[room.host.id]||0} · ${esc(room.guest?.name||'Waiting')} ${room.guest?room.scores[room.guest.id]||0:''}</span><strong id="trivia-clock">${room.status==='waiting'?'Waiting':room.status==='finished'?'Finished':seconds()+'s'}</strong></div>${room.status==='waiting'?`<section class="card"><h2>Invite a friend</h2><p>Share this six-character room code with another account. The clock starts when they join.</p><strong class="room-code">${esc(room.code)}</strong><button class="secondary" data-trivia="copy">Copy code</button></section>`:''}${room.status==='finished'?`<section class="card"><h2>Round complete</h2><p>${room.scores[me]===room.scores[opponent?.id]?'A tie. Well played.':room.scores[me]>room.scores[opponent?.id]?'You won this round.':'Your friend won this round.'}</p></section>`:''}`}
    return `<div class="trivia-status"><span>Solo score <strong>${solo?.score||0}</strong></span><strong id="trivia-clock">${solo?.ends?seconds()+'s':''}</strong></div>${solo?.ends&&seconds()===0?'<section class="card"><h2>Time is up</h2><p>Start another round to try the board again.</p></section>':''}`}
  function done(id,choice){return room?room.claims.some(c=>c.tile_key===(mode==='jeopardy'?id:`${id}:${choice}`)):mode==='jeopardy'?solo?.used.has(id):solo?.used.has(`${id}:${choice}`)}
  function tried(id,choice){return !!room?.attempts.some(a=>a.tile_key===(mode==='jeopardy'?id:`${id}:${choice}`))}
  function render(){if(!root)return;if(!mode){root.innerHTML=`<button class="text-button" data-nav="challenges">← Quizzes & games</button><span class="eyebrow">PLAY THE SCRIPTURES</span><h1>The question is yours.</h1><p class="lead">Choose a timed solo round or challenge a friend with a room code. Answers and scores are checked by the server.</p><div class="challenge-grid"><button class="card challenge-card" data-trivia="select" data-mode="answer-board"><span class="eyebrow">ANSWER BOARD</span><h2>Family Feud style</h2><p>Find four biblical answers in each round. Higher rows earn more points.</p></button><button class="card challenge-card" data-trivia="select" data-mode="jeopardy"><span class="eyebrow">CATEGORY BOARD</span><h2>Jeopardy style</h2><p>Pick a clue, then reply in question form across six categories.</p></button></div><p class="footnote">The answer board point order is curated for play. It does not represent an actual survey.</p>`;return}
    const started=!!solo||!!room;
    root.innerHTML=`<button class="text-button" data-trivia="back">← Games</button><span class="eyebrow">${mode==='jeopardy'?'CATEGORY BOARD':'ANSWER BOARD'}</span><h1>${mode==='jeopardy'?'Clues across Scripture.':'Name what the Bible names.'}</h1>${!started?`<p class="lead">Solo has a two-minute clock. A friend room starts a three-minute clock when a second account joins.</p><div class="trivia-actions"><button class="primary" data-trivia="solo">Timed solo</button><button class="secondary" data-trivia="create">Create friend room</button><label class="room-join">Join a room<input id="room-input" placeholder="Six-character code" maxlength="6" autocomplete="off" autocapitalize="characters"></label><button class="secondary" data-trivia="join">Join</button></div>`:`${status()}${room?.status==='waiting'||room?.status==='finished'||solo?.ends&&seconds()===0?'':mode==='jeopardy'?jeopardyBoard():answerBoard()}`}${feedback?`<div class="card trivia-feedback" role="status"><strong>${feedback.correct?'✓ Correct':'↻ Try the next one'} · ${feedback.points||0} points</strong><p>${esc(feedback.explanation)}</p><small>${esc(feedback.reference)}</small></div>`:''}<p class="footnote">Scripture references use KJV numbering. Orthodox Psalter numbers can differ.</p>`;
  }
  function jeopardyBoard(){const items=library.jeopardy,cats=[...new Set(items.map(q=>q.category))];return `<div class="jeopardy-board">${cats.map(cat=>`<div class="jeopardy-column"><h3>${esc(cat)}</h3>${items.filter(q=>q.category===cat).map(q=>`<button data-trivia="open" data-id="${esc(q.id)}" ${done(q.id)||tried(q.id)?'disabled':''}>${done(q.id)?'✓':tried(q.id)?'—':q.points}</button>`).join('')}</div>`).join('')}</div>${open?clue(items.find(q=>q.id===open)):''}`}
  function answerBoard(){const items=library.answerBoard;return `<div class="feud-list">${items.map(q=>`<button class="card feud-round" data-trivia="open" data-id="${esc(q.id)}"><strong>${esc(q.prompt)}</strong><span>${[0,1,2,3].filter(n=>done(q.id,n)).length}/4 revealed</span></button>`).join('')}</div>${open?clue(items.find(q=>q.id===open)):''}`}
  function clue(q){if(!q)return '';const choices=q.choices.map((choice,i)=>`<button data-trivia="answer" data-id="${esc(q.id)}" data-choice="${i}" ${busy||done(q.id,i)||tried(q.id,i)||mode==='jeopardy'&&(done(q.id)||tried(q.id))?'disabled':''}>${mode==='jeopardy'?`${q.answerForm} ${esc(choice)}?`:esc(choice)}${done(q.id,i)?' ✓':''}</button>`).join('');return `<section class="card trivia-clue" id="active-clue"><span class="eyebrow">${mode==='jeopardy'?`${esc(q.category)} · ${q.points} POINTS`:'FOUR SCRIPTURAL ANSWERS · 40 / 30 / 20 / 10'}</span><h2>${esc(q.prompt)}</h2><div class="trivia-choices">${choices}</div><p class="small">${mode==='jeopardy'?'Choose your response in question form.':'Choose every biblical answer. A correct answer can be claimed once in a friend room.'}</p></section>`}
  async function refresh(){if(!room||!root)return;try{room=await ctx.api(`/study/trivia/room?code=${encodeURIComponent(room.code)}`);render()}catch(e){ctx.toast(e.message);stop()}}
  function clock(){stop();tick=setInterval(()=>{if(!root){stop();return}const el=root.querySelector('#trivia-clock');if(el&&el.textContent.endsWith('s'))el.textContent=seconds()+'s';if((room?.status==='active'||solo?.ends)&&seconds()===0){if(room)refresh();else render();stop()}},1000);if(room)poll=setInterval(refresh,3500)}
  async function click(e){if(!root||!root.contains(e.target))return;const button=e.target.closest('[data-trivia]');if(!button)return;const action=button.dataset.trivia;try{
    if(action==='back'){hide();ctx.back();return}
    if(action==='retry'){library=null;await load();render();return}
    if(action==='select'){mode=button.dataset.mode;solo=room=open=feedback=null;render();return}
    if(action==='solo'){solo={score:0,used:new Set(),ends:Date.now()+120000};feedback=null;render();clock();return}
    if(action==='copy'){await navigator.clipboard.writeText(room.code);ctx.toast('Room code copied.');return}
    if(action==='create'||action==='join'){if(!ctx.user()?.registered){ctx.promptSignup();return}button.disabled=true;room=await ctx.api(`/study/trivia/${action}`,'POST',action==='create'?{mode}:{code:root.querySelector('#room-input')?.value});if(action==='join')mode=room.mode;open=feedback=null;render();clock();return}
    if(action==='open'){open=button.dataset.id;feedback=null;render();root.querySelector('#active-clue')?.scrollIntoView({block:'nearest',behavior:'smooth'});return}
    if(action==='answer'){if(busy||seconds()===0||room?.status!=='active'&&room)return;busy=true;button.disabled=true;const id=button.dataset.id,choice=Number(button.dataset.choice);try{const result=await ctx.api(room?'/study/trivia/answer':'/study/trivia/check','POST',{mode,id,choice,...(room?{code:room.code}:{})});feedback=result;if(room)room=result.room;else{if(mode==='jeopardy')solo.used.add(id);else solo.used.add(`${id}:${choice}`);solo.score+=result.points}if(mode==='jeopardy')open=null;render()}finally{busy=false;render()}return}
  }catch(error){busy=false;button.disabled=false;ctx.toast(error.message);if(room)refresh()}}
  return {show:async(el,options)=>{hide();root=el;ctx=options;root.innerHTML='<div class="loading">Opening games…</div>';try{await load();render()}catch(e){root.innerHTML=`<div class="empty error">${esc(e.message)} <button data-trivia="retry">Try again</button></div>`}},hide,click};
})();
